services:
    lexnetictodofrontend:
      container_name: lexnetictodofrontend
      build:
        context: .
        dockerfile: Dockerfile

      command: sleep infinity
      volumes:
        - ../..:/workspaces:cached
      ports:
        - 8000:8000